language: python

python:
    - "2.7"
    - "3.5"

env:
    global:
        secure: "DClj2Eyr7bXx/m+gd01jIq/w1fVhXYpnlZN61eXiFLHBTbEvUSLzyB5pZCIkpaE4tY82QCdCEP3ZzHBJaxxsF6qKx1cCvOamCSM0fNY4TM/9PK2sKzKCVjmV04DFCgnKlKLTBZEyLSNuC6+8mnGHD0fC89vRbHAZzHNO7u4/MkJiMXPwKUKZ8/LUJoWJx5yfM3dDJ+xlHFpnoVy0Rtg7KWyZyy/5Ywzm2p3k4+3rNP7uL020v7p0abQksSega24lGhTYUAoJ5+2OHk8UDgmnsk/N4f4RY2rNkiFXIAICYmxRzJXIkJW+Iak0xppOblTWeJBxUse1Tn+TMuAjCNCDGSl93ZlVY5GMvvcWOCBUY20OmwgHHYM0iUw3M6KQZuIWj8es4Nh1X/tlbZg9i26ihnlGJzwrGMQOmTvqiF4KOgfLmCx1oAoKlxK9HvG5g//Vd2trq7AB4fwnkx0f0rZ9MWerjpR9xRw/l8+bQzoS8Sp2qTcDrdn9sR5puvcW4Jh8w4fP/XW6WpL0U95SWJ5fU/xZgQpbUmoHZQt2y9rGufWRuk/Z9duaDfpcsyeM5+gI+J/BHss4OWA0Hxld0wjZj7+EJMq8GcBKZBGSCLTR5CNtEm8Ihk9XI257DxIla1qFWm+tO8dgZ4L9hp7YZ9zQoc8agPFo3mjd92tUN3G0c5E="

install:
    - sleep 1

script:
    - python --version

jobs:
    include:
        - stage: merge
          script: ./merge.sh
