language: python

python:
    - "2.7"
    - "3.5"

install:
    - pip install -r requirements.txt

script:
    - python --version

jobs:
    include:
        - stage: merge
          script: ./merge.sh
